### ISSUE TITLE
Add a notation to Readme about Twitter and Instagram support

### ISSUE THREAD

**Issue by neSpecc** [editor-js/embed#10]

**Comment by wilfredonoyola** [comment]
x2

**Comment by wilfredonoyola** [comment]
Hey @neSpecc , Did you integrate twitter and instagram on you project?

**Comment by wilfredonoyola** [comment]
I solved this! 

Important: Instagram and Twitter do not use iframe to embed the media, 

I did like that:

1. Added a basic regex to Twitter and <%= remote_id %> returns  "${username}/$(id)", so I used 'react-twitter-embed' to render the status/videos with $(id).
2. Regarding with Instagram, I used the "source" attribute (This is typing / paste from user.)
   Example: If the user paste "https://www.instagram.com/p/B24c53TA8mO" in the editor, the source atrribute is the same. Later I used "react-instagram-embed" for render the post.

3. I implented easy way to display a placeholder to twitter and instagram in the editor.
![placelholder](https://user-images.githubusercontent.com/1428168/65741108-48156500-e0a8-11e9-9d44-6ff1c2530bb5.PNG)


```
embed: {
    class: Embed,
    config: {
        services: {
            youtube: true,
            coub: true,
            twitter: {
                regex: /^https?:\/\/twitter\.com\/(?:#!\/)?(\w+)\/status(?:es)?\/(\d+)(?:\/.*)?$/,
                embedUrl: '<%= remote_id %>',
                html: '<div style="width: 100%; height: 100px; background-color: #1C9CEA; text-align: center; color: #ffffff; padding-top: 40px">Twitter embedded.</div>',
                height: 300,
                width: 600,
                id: (ids) => ids.join('/')
            },
            instagram: {
                regex: /(https?:\/\/(?:www\.)?instagram\.com\/p\/([^/?#&]+)).*/,
                embedUrl: '<%= remote_id %>',
                html: '<div style="width: 100%; height: 100px; background-color: #DB2E6E; text-align: center; color: #ffffff; padding-top: 40px">Instagram embedded.</div>',
                height: 300,
                width: 600
            }
        }
    }
},
```

**Comment by neSpecc** [comment]
@wilfredonoyola yes, that can be a one of solution. Maybe it will be a useful to add post's url at the blocks that will allow to view attached posts.

> Instagram and Twitter do not use iframe to embed the media

It is the reason why they are not supported by Embed Block for now.

Another way is to create separate plugins for Twitter and Instagram blocks. These plugins should provide a `prepare` method (returning Promise) that will synchronusly load Twitter's or Instagram's SDK script. And in `render` method they will call a special SDK's method to render widget.

**Comment by kornarakis** [comment]
@neSpecc @wilfredonoyola  Instragram has iframe embed 
```
instagram: {
    regex: /https?:\/\/www\.instagram\.com\/p\/([^\/\?\&]+)\/?/,
    embedUrl: 'https://www.instagram.com/p/<%= remote_id %>/embed',
    html: '<iframe width="400" height="505" style="margin: 0 auto;" frameborder="0" scrolling="no" allowtransparency="true"></iframe>',
    height: 505,
    width: 400
},
```

**Comment by neSpecc** [comment]
@kornarakis Cool. If you have a time, you can send a PR implementing this feature.

**Comment by kornarakis** [comment]
> @kornarakis Cool. If you have a time, you can send a PR implementing this feature.

Ok done :) https://github.com/editor-js/embed/pull/17

**Comment by neSpecc** [comment]
Twitter and Instagram support added by #17

**Comment by Smokietr** [comment]
Pinterest has iframe embed

`pinterest: {
      regex: /https?:\/\/([^\/\?\&]*).pinterest.com\/pin\/([^\/\?\&]*)\/?$/,
      embedUrl: 'https://assets.pinterest.com/ext/embed.html?id=<%= remote_id %>',
      html: "<iframe scrolling='no' frameborder='no' allowtransparency='true' allowfullscreen='true' style='width: 100%; min-height: 400px; max-height: 1000px;'></iframe>",
      id: function (e) {
          return e[1];
     }
}`
