### ISSUE TITLE
not working with Typescript

### ISSUE THREAD

**Issue by taishi55** [editor-js/embed#101]
I tried to use this plugin with typescript. It seems not working. 

I look forward to hearing some advice. 

So far, I tried `npm i --save-dev @types/editorjs__embed` and adding `declare module '@editorjs/embed';` on `external.d.ts`

**Comment by thmarx** [comment]
Same here!
In typescript the embed block is not shown in the menu.

**Comment by ludusrusso** [comment]
same here

**Comment by TheAlphamerc** [comment]
Same here

**Comment by legezam** [comment]
same here

**Comment by legezam** [comment]
Aah, it works it just doesn't have a UI. This issue can be closed.
If you want to trigger embed, go to youtube, and paste the url of a video from the address bar (not the embed code!) into a plain paragraph block and it will work automagically.
Perhaps it would be beneficial to make this a bit more clear in the readme or somewhere.

**Comment by TheAlphamerc** [comment]
Yeah, and having a UI would also be great.

**Comment by RedLionHeart** [comment]
> 

haha thanks for the comment. I would never have guessed

**Comment by hiep-notaloop** [comment]
It does not work if the link includes the channel id. For example, https://www.youtube.com/watch?v=ypa_7HT2UGQ&ab_channel=NotaLoop

**Comment by kimyvgy** [comment]
Same here, Embed does not show in the menu.

**Comment by mohamedsahel** [comment]
Same here

**Comment by Sozialarchiv** [comment]
Meanwhile it should work with typescript.

> Same here, Embed does not show in the menu.

This is not a bug. It a feature. Just add the url in Paragraph.
