### ISSUE TITLE
use twitter embed code

### ISSUE THREAD

**Issue by SimonVillage** [editor-js/embed#102]
I am trying to understand the value of the iframe used for twitter but I can't see any reason?
It also seems to render with a fixed height?

Is it possible to add the twitter native way somehow?

**Comment by Abhii5496** [comment]
> I am trying to understand the value of the iframe used for twitter but I can't see any reason? It also seems to render with a fixed height?
> 
> Is it possible to add the twitter native way somehow?

#124 , i have added the official twitter embed 👍
