### ISSUE TITLE
Help! Embed not working

### ISSUE THREAD

**Issue by wonder-image** [editor-js/embed#117]
Hi I didn't see the embed icon and I extended the class like this
```
class CustomEmded extends Embed {
    
    static get toolbox() {
        return {
            title: 'Embed',
            icon: '<svg width="20" height="20" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 13a5 5 0 0 1 0-6M14 11a5 5 0 0 1 0 6"></path><line x1="14" y1="7" x2="14" y2="7"></line><line x1="10" y1="17" x2="10" y2="17"></line></svg>'
        };
    }
    
}
```
Then I added the class to the tools array
```
var editor = EditorJS({
  tools: {
    embed: {
        class: CustomEmded,
    },
  },
});
```
Now I see the icon and text but pressing doesn't work

https://github.com/editor-js/embed/assets/114833396/c6466b07-c480-43ad-a88c-bce250944198

I have no errors in the console

**Comment by bettysteger** [comment]
@wonder-image you must also overwrite the render function, because the original Embed Block Tool does not show an URL input field. 

I just did this here: https://gist.github.com/bettysteger/9d613904c2b14c15182e6204863b79b3

**Comment by wonder-image** [comment]
Thanks a lot for the answer but now I have this error in console:

```
Block «embed» skipped because saved data is invalid
```


https://github.com/editor-js/embed/assets/114833396/99e0f7d5-6b14-4795-a218-e9455ecb6fcc

**Comment by bettysteger** [comment]
@wonder-image that message is fine, it should not save until you put in an URL in the input field!

**Comment by wonder-image** [comment]
https://github.com/editor-js/embed/assets/114833396/ba53e0c2-62bc-4f7c-bbe6-007f1682a2ea

**Comment by bettysteger** [comment]
@wonder-image this is not an iframe embed, it is an embed service for youtube, vimeo, etc, you see a list here: https://github.com/editor-js/embed?tab=readme-ov-file#list-of-services-supported

**Comment by wonder-image** [comment]
Thanks, but is it possible to still accept any type of URL even if it is not included in the services?

**Comment by bettysteger** [comment]
you can add custom services: https://github.com/editor-js/embed?tab=readme-ov-file#add-more-services 

but i am not sure if it works with my gist then!
