### ISSUE TITLE
custom service not work, and toolbox no icon

### ISSUE THREAD

**Issue by falstack** [editor-js/embed#13]
![image](https://user-images.githubusercontent.com/16357724/59922726-ff745d00-9463-11e9-918e-340b1fbe7e1b.png)

![image](https://user-images.githubusercontent.com/16357724/59922756-0e5b0f80-9464-11e9-91c8-096a3e698d21.png)

there is my code：https://github.com/calibur-tv/Mahoo/blob/ae018bf80006e6bde11cfac02461263ea937327b/components/editor/index.vue#L105

**Comment by gohabereg** [comment]
Hi @falstack 
Thank you for feedback. We already know about issue with the custom config — it will be fixed in the next release.

Embed tool do not have icon in toolbox, you just need to paste the link into paragraph

**Comment by Rathpanha** [comment]
Hi @gohabereg 
I am facing that problem too. I'm trying to embed Facebook video. Shouldn't be Facebook include into this plugin without custom build since it's quite popular.

**Comment by gohabereg** [comment]
Hi @Rathpanha 
Not sure if Facebook embeded posts are working the same way as (for example) Youtube. You can raise an issue for Facebook support
