### ISSUE TITLE
Config doesn't pass down with latest EditorJS version (2.20.2)

### ISSUE THREAD

**Issue by ryandunnewold** [editor-js/embed#60]
When I upgrade to the latest EditorJS version (2.20.2) the config settings do not get passed down to the Embed tool (all services are turned on and my custom services do not work). I don't know if this is an issue with EditorJS or if something needs to be upgraded in the embed package.

Happy to help debug anyway I can!

**Comment by gastonfc** [comment]
I found the same problem using EditorJS 2.20.1

**Comment by m-alzam** [comment]
Same problem with Editor.js 2.22.2

**Comment by onurmatik** [comment]
The problem is not the embed tool but the Editorjs itself. Versions of Editorsj later than 2.19.3 are not passing the config parameters to the tool. I rolled back to the 2.19.3 and it is working as it should.

**Comment by neSpecc** [comment]
Resolved
