### ISSUE TITLE
All services load despite config

### ISSUE THREAD

**Issue by philipaarseth** [editor-js/embed#72]
Setting the keys according to https://github.com/editor-js/embed/blob/master/docs/services.md to false does nothing and still loads all services as of "@editorjs/embed": "^2.4.6".

https://imgur.com/a/4y0MB3p

```
config: {
  services: {
    youtube: true,
    vimeo: true,
    imgur: false,
    twitter: false
  }
}
```

**Comment by neSpecc** [comment]
Resolved
