### ISSUE TITLE
Adding gist github service

### ISSUE THREAD

**Issue by jefcolbi** [editor-js/embed#82]
Hi, i am trying to add gist github service but it is not working. This is what i tried

```
'github': {
              regex: /https?:\/\/gist.github.com\/([^\/\?\&]*)\/([^\/\?\&]*)/,
              embedUrl: 'https://gist.github.com/<%= remote_id %>',
              html: "<iframe height='300' scrolling='no' frameborder='no' allowtransparency='true' allowfullscreen='true' style='width: 100%;'></iframe>",
              height: 300,
              id: (groups) => groups.join('/')
          }
```

What am i doing wrong?

**Comment by rajeshbanoth** [comment]
> Hi, i am trying to add gist github service but it is not working. This is what i tried
> 
> ```
> 'github': {
>               regex: /https?:\/\/gist.github.com\/([^\/\?\&]*)\/([^\/\?\&]*)/,
>               embedUrl: 'https://gist.github.com/<%= remote_id %>',
>               html: "<iframe height='300' scrolling='no' frameborder='no' allowtransparency='true' allowfullscreen='true' style='width: 100%;'></iframe>",
>               height: 300,
>               id: (groups) => groups.join('/')
>           }
> ```
> 
> What am i doing wrong?

@jefcolbi  if you could embedd GitHub gist please let me now  I am also facing similar issue

**Comment by jefcolbi** [comment]
I have been able to add it yes

**Comment by rajeshbanoth** [comment]
> I have been able to add it yes
@jefcolbi can you please share me  the  code I was unable to add git gist to editor

**Comment by jefcolbi** [comment]
@rajeshbanoth https://github.com/editor-js/embed/pull/91/files

**Comment by jefcolbi** [comment]
#91

**Comment by neSpecc** [comment]
Still on review
